name: More Audio Settings

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: ['more-audio-settings/v*']
    paths:
      - 'more-audio-settings/**'
      - 'shared/**'
      - '.github/workflows/build-more-audio-settings.yml'
      - '.github/workflows/_build-mod.yml'
  pull_request:
    branches: [main]
    paths:
      - 'more-audio-settings/**'
      - 'shared/**'
      - '.github/workflows/build-more-audio-settings.yml'
      - '.github/workflows/_build-mod.yml'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref_type != 'tag' }}

jobs:
  build:
    uses: ./.github/workflows/_build-mod.yml
    with:
      project: more-audio-settings
      module: more-audio-settings
      title: More Audio Settings

